// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    CommentList: typeof import('./src/components/Comments/components/CommentList.vue')['default']
    Comments: typeof import('./src/components/Comments/index.vue')['default']
    Edit: typeof import('./src/components/Comments/components/Edit.vue')['default']
    FaBrandsMarkdown: typeof import('./src/components/Icon/fa-brands-markdown.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    MobileNav: typeof import('./src/components/MobileNav.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}
